version: '3.5'

services:

  role-based-access-control-app-1:
    container_name: app-1
    image: lombocska/role-based-access-control-example
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL_APP: INFO
      DB_HOST: app-postgres
      DB_PORT: 5432
      LIQUIBASE_CONTEXTS: dev
